name: Rugsafe dApp Deployment

on:
  push:
    branches: [ master, dev/pipeline-setup ]
  pull_request:
    branches: [ master, dev/pipeline-setup ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: setup nvm
      run: export NVM_DIR=~/.nvm ; source ~/.nvm/nvm.sh

    - name: list node version
      run: node -v;
   

    - name: list node version
      run: nvm use v20.15.1;
   
    - name: yarn install
      run: yarn

    - name: Kill Tmux Session and Processes
      run: |
        tmux send-keys -t rugsafe-dapp C-c || true
        sleep 5 
        tmux kill-session -t rugsafe-dapp || true

    - name: Run protocol
      run: |
        tmux new -d -s rugsafe-dapp 'sh -c yarn dev"'