name: Rugsafe dApp Deployment

on:
  push:
    branches: [ master, dev/pipeline-setup ]
  pull_request:
    branches: [ master, dev/pipeline-setup ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: setup nvm
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
        nvm install v20.15.1
        nvm use v20.15.1

    - name: list node version
      run: node -v

    - name: yarn install
      run: yarn